### ISSUE TITLE
Option override doesn't work

### ISSUE THREAD

**Issue by lorantkurthy** [mikejdorm/sftp_ex#8]
Can not override options in default options.
If I change the order of merging, it works:

  def connect(opts) do
      opts = @default_opts |> Keyword.merge(logging_functions())
                                         |> Keyword.merge(opts)

**Comment by jjcarstens** [comment]
@mikejdorm It looks like this didn't get fixed with the last release. #10 was just merged into branch `mikejdorm:issue6` instead of into master. We'll need another list
